FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install

# Set the server port
ENV PORT=3000
EXPOSE 3000

# Launch:
CMD ["yarn", "start"]
